@ECHO OFF
ECHO                                                           ³
ECHO  Please wait while Program Manager Starts...              ³
ECHO                                                           ³
ECHO -----------------------------------------------------------
IF VER="5.0"
PROGMAN.BAT
IF VER="5.1"
PROGMAN.BAT
IF VER="5.2"
PROGMAN.BAT
IF VER="5.3"
PROGMAN.BAT
IF VER="5.4"
PROGMAN.BAT
IF VER="5.5"
PROGMAN.BAT
IF VER="5.6"
PROGMAN.BAT
IF VER="5.7"
PROGMAN.BAT
IF VER="5.8"
PROGMAN.BAT
IF VER="5.9"
PROGMAN.BAT
IF VER="6.0"
PROGMAN.BAT
IF VER="6.1"
PROGMAN.BAT
IF VER="6.2"
PROGMAN.BAT
IF VER="6.3"
PROGMAN.BAT
IF VER="6.4"
PROGMAN.BAT
IF VER="6.5"
PROGMAN.BAT
IF VER="6.6"
PROGMAN.BAT
IF VER="6.7"
PROGMAN.BAT
IF VER="6.8"
PROGMAN.BAT
IF VER="6.9"
PROGMAN.BAT
IF VER="7.0"
PROGMAN.BAT
IF VER="7.1"
PROGMAN.BAT
CLS
ECHO                                                           ³
ECHO  You cannot Run Program Manager, You need atleast         ³
ECHO  MS-DOS 5.0 to 7.1, Press any Key to return to DOS...     ³
ECHO                                                           ³
PAUSE -----------------------------------------------------------
CD..
CLS
VER
