@ECHO OFF
CD..
CD IDQYN
ECHO -----------------------------------------------------------
ECHO                                                           ³
ECHO  Do you want to Delete Or Install Program Manager 1.3?    ³
ECHO  Requirements in README.TXT file...                       ³
ECHO                                                           ³
ECHO ----------------[CANCEL,DELETE,INSTALL]--------------------
